# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

#- script: npm ci
- script: npm install -g @angular/cli
  displayName: 'npm install'

#- script: npm run lint
#  displayName: 'npm run lint'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'TriviaGameNG'
    organization: 'craigastuckey-github'
    scannerMode: 'MSBuild'
    projectKey: 'TriviaGameNG'
    projectName: 'TriviaGameNG'

- script: npm run build-ci
  displayName: 'Build'
  workingDirectory: TriviaGameNG/
  
- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '100'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(c46194b8-1218-46ee-82a1-de3fbcd60cc2)'
    appType: 'webAppLinux'
    WebAppName: '1904-TriviaGame-Angular'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'NODE|lts'